export const pizzaFunFacts = [
  "The first pizzeria in the United States was opened in 1905 by Gennaro Lombardi in New York City. Today, there are hundreds of AVPN-certified pizzerias worldwide maintaining authentic Neapolitan traditions!",
  "According to AVPN regulations, a true Neapolitan pizza must bake for only 60 to 90 seconds in a wood-fired oven at a blistering 485°C (905°F).",
  "Authentic Neapolitan pizza dough is a study in simplicity. By AVPN rules, it requires exactly four ingredients: water, salt, yeast, and highly refined Type 00 or Type 0 wheat flour.",
  "The classic Pizza Margherita was allegedly created in 1889 to honor the Queen of Italy. Its toppings—tomato, mozzarella, and basil—proudly represent the red, white, and green of the Italian flag.",
  "In 2017, the art of the Neapolitan 'Pizzaiuolo' (pizza maker) was officially inscribed on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity.",
  "The Associazione Verace Pizza Napoletana (AVPN) was founded in June 1984 in Naples. Its strict mission is to promote and protect the true Neapolitan pizza across the globe.",
  "A true AVPN Neapolitan pizza should be soft, elastic, tender, and fragrant. It is never meant to be rigid or crunchy, which is why it's traditionally eaten by folding it into a 'libretto' (little book)!",
  "During the late 19th century, pizza was primarily sold by street vendors in Naples to the working class. It was considered 'peasant food' until King Umberto I and Queen Margherita famously gave it their royal approval.",
  "The word 'pizza' was first documented in 997 AD in a Latin text from the southern Italian town of Gaeta. It demanded that twelve pizzas be given to the local bishop every Christmas and Easter.",
  "The mathematical formula that dictates the maximum number of pieces a circular pizza can be cut into with a given number of straight cuts is aptly named the 'Lazy Caterer's sequence'.",
  "October is officially National Pizza Month in the United States. The designation was created in 1984 by the publisher of Pizza Today magazine.",
  "Despite its name, the Hawaiian pizza was not invented in Hawaii! It was created in Ontario, Canada, in 1962 by Sam Panopoulos, a Greek immigrant inspired by the sweet and savory flavors of Chinese cuisine.",
  "In Japan, it is incredibly popular to top pizzas with unconventional ingredients like squid, sweet corn, potatoes, and drizzles of mayonnaise.",
  "Scotland has a unique, indulgent take on the dish known as the 'pizza crunch'. It consists of a pizza that is heavily battered and deep-fried, often served alongside french fries.",
  "In 2001, pizza officially went to space. A specially vacuum-sealed, 6-inch salami pizza was delivered to the International Space Station in a promotional stunt that cost over a million dollars.",
  "The Guinness World Record for the largest pizza ever made was set in Los Angeles in 2023. It covered nearly 14,000 square feet, required 13,653 pounds of dough, and yielded roughly 68,000 slices!",
  "The most expensive commercially available pizza in the world is the 'Louis XIII' in Italy, created by Chef Renato Viola. It costs a staggering $12,000, features three types of caviar and lobster, and takes 72 hours to prepare.",
  "The longest pizza delivery on record spanned an incredible 19,870 kilometers (over 12,300 miles)! In 2006, a pizza was hand-delivered all the way from Madrid, Spain, to Wellington, New Zealand.",
  "The average American eats roughly 46 slices of pizza every single year. This high demand contributes to the roughly 3 billion pizzas sold annually in the United States alone.",
  "Super Bowl Sunday is widely considered the biggest day of the year for pizza delivery in the US. Delivery drivers log an estimated 4 million miles on the road in just that one evening!",
];
