name: Wake Up Render Backend
on:
  schedule:
    - cron: "47 3 * * *"
  workflow_dispatch:
jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          curl -I https://api.avpnmap.app/admin/wake \
            -H "x-admin-key: ${{ secrets.ADMIN_SECRET }}"
